apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-appchain-barnacle
spec:
  selector:
    matchLabels:
      app: application-appchain-barnacle
  template:
    metadata:
      labels:
        app: application-appchain-barnacle
    spec:
      serviceAccountName: subql-ksa
      containers:
      - name: cloud-sql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.17
        command:
          - "/cloud_sql_proxy"
          - "-instances=octopus-dev-309403:asia-east1:octopus=tcp:5432"
        securityContext:
          # The default Cloud SQL proxy image runs as the
          # "nonroot" user and group (uid: 65532) by default.
          runAsNonRoot: true
        # Resource configuration depends on an application's requirements. You
        # should adjust the following values based on what your application
        # needs. For details, see https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
        resources:
          requests:
            # The proxy's memory use scales linearly with the number of active
            # connections. Fewer open connections will use less memory. Adjust
            # this value based on your application's requirements.
            memory: "2Gi"
            # The proxy's CPU use scales linearly with the amount of IO between
            # the database and the application. Adjust this value based on your
            # application's requirements.
            cpu:    "1"
      - name: application-appchain-barnacle-node
        image: "gcr.io/octopus-dev-309403/octopus-subql-node:0.15.1"
        args:
          - -f=/workdir
          - --subquery-name=barnacle
          - --migrate
          - --network-endpoint=wss://barnacle.rpc.testnet.oct.network:9944
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: octopus-subql
              key: username
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: octopus-subql
              key: password
        - name: DB_DATABASE
          valueFrom:
            secretKeyRef:
              name: octopus-subql
              key: database
      - name: application-appchain-barnacle-query
        image: "gcr.io/octopus-dev-309403/octopus-subql-query:0.5.1"
        ports:
        - containerPort: 3001
          name: http-rpc
        args:
          - --name=barnacle
          - --playground
        env:
        - name: PORT
          value: "3001"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: octopus-subql
              key: username
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: octopus-subql
              key: password
        - name: DB_DATABASE
          valueFrom:
            secretKeyRef:
              name: octopus-subql
              key: database
