specVersion: 0.0.1
description: ''
repository: https://github.com/octopus-network/octopus-subql
schema: ./schema.graphql
network:
  endpoint: wss://barnacle.rpc.testnet.oct.network:9944

dataSources:
  - name: main
    kind: substrate/Runtime
    startBlock: 1
    mapping:
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Deposit
        - handler: handleCall
          kind: substrate/CallHandler
